#Name of the application
spring:
  application:
    name: demo_searchService

#Eureka server url for registering
#This is eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
#register url to server

instance:
  hostname: localhost

server:
  port: 8986